### ISSUE TITLE
Not compatible with Python3

### ISSUE THREAD

**Issue by corsch** [CroweCybersecurity/ad-ldap-enum#22]
Unfortunately ad-ldap-enum.py is not compatible with python3.

Can anyone estimate how long it would take to migrate the script to python3?

**Comment by ParityInfosec** [comment]
I don't see any replies to date; I just ported over my quick edit to make it python3/ldap3 compatible.  Check it out!

> Unfortunately ad-ldap-enum.py is not compatible with python3.
> 
> Can anyone estimate how long it would take to migrate the script to python3?

I don't see any replies to date; I just forked and ported over my quick edits to make it python3/ldap3 compatible.  Check it out if you are still [looking!](https://github.com/ParityInfosec/ad-ldap-enum)

**Comment by corsch** [comment]
Sorry for the late answer and thank you for porting ad-ldap-enum to Python3

**Comment by fabaff** [comment]
The change for Python 3 are only available in the fork. Any changes that those changes are included here?

**Comment by raul5660** [comment]
fixed with merge #23
