### ISSUE TITLE
Unable to Bind Output

### ISSUE THREAD

**Issue by Zamanry** [CroweCybersecurity/ad-ldap-enum#24]
If the tool is unable to bind through a null/authenticated or insecure/secure LDAP connection, the tool outputs an error rather than a statement stating "Unable to bind to requested LDAP connection." See the current output now:

![ad-ldap-enum-output](https://user-images.githubusercontent.com/28152647/113749036-294d5100-96d7-11eb-889c-22fa6ae5e399.png)

**Comment by raul5660** [comment]
@Zamanry  Would it be possible to spin up a DC that allows null auth and validate the functionality works as intended?

**Comment by raul5660** [comment]
Working on it.

commit: f4173dc14c5680580b42af755a7154a811611e02
