### ISSUE TITLE
Large Group Parsing Error

### ISSUE THREAD

**Issue by 3x14** [CroweCybersecurity/ad-ldap-enum#25]
Ran the following:
`python3 ad-ldap-enum.py -l <IP> -d <domain> -u <username> -p <password>`

![image](https://user-images.githubusercontent.com/11723613/118822941-96cbd000-b886-11eb-8b55-4713189aae2d.png)

**Comment by raul5660** [comment]
Looks like this is not for nested groups but for groups with a large number of users within it. A fix was identified. 

replace line 473 with `sanatized_group_dn = str(group_dn).replace('(', '\\28').replace(')', '\\29').replace('*', '\\2a').replace('\\', '\\5c')`

**Comment by raul5660** [comment]
Fix hasn't been pushed yet. lets keep this open until we have a pull request

**Comment by raul5660** [comment]
Why?

**Comment by Zamanry** [comment]
I've had hundreds of internal penetration tests run this tool, and have not encountered this issue. Reading the above comments, this may have been fixed already, but regardless, since the rewrite, haven't seen it. Therefore, closing.
